//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjekt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlaEntities : DbContext
    {
        public OlaEntities()
            : base("name=OlaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sl_GrupaTw> sl_GrupaTw { get; set; }
        public virtual DbSet<sl_ModelTowar> sl_ModelTowar { get; set; }
        public virtual DbSet<sl_Rabat> sl_Rabat { get; set; }
        public virtual DbSet<sl_StawkaVAT> sl_StawkaVAT { get; set; }
        public virtual DbSet<tw__Towar> tw__Towar { get; set; }
        public virtual DbSet<ui_Funkcja> ui_Funkcja { get; set; }
        public virtual DbSet<ui_Kolor> ui_Kolor { get; set; }
        public virtual DbSet<ui_Modul> ui_Modul { get; set; }
        public virtual DbSet<ui_ModulPowiazany> ui_ModulPowiazany { get; set; }
    }
}
