//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ui_Kolor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ui_Kolor()
        {
            this.ui_Modul = new HashSet<ui_Modul>();
        }
    
        public int uic_Id { get; set; }
        public string uic_Nazwa { get; set; }
        public string uic_SerwisTloGora { get; set; }
        public string uic_SerwisTloDol { get; set; }
        public string uic_SerwisTekst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ui_Modul> ui_Modul { get; set; }
    }
}
