//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ui_ModulPowiazany
    {
        public int uimp_Id { get; set; }
        public int uimp_IdModulu { get; set; }
        public int uimp_Typ { get; set; }
        public int uimp_IdObiektu { get; set; }
        public int uimp_Pozycja { get; set; }
        public int uimp_Styl { get; set; }
        public string uimp_Napis { get; set; }
    
        public virtual ui_Modul ui_Modul { get; set; }
    }
}
