//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ui_Modul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ui_Modul()
        {
            this.ui_Funkcja = new HashSet<ui_Funkcja>();
            this.ui_Modul1 = new HashSet<ui_Modul>();
            this.ui_ModulPowiazany = new HashSet<ui_ModulPowiazany>();
        }
    
        public int uim_Id { get; set; }
        public int uim_Typ { get; set; }
        public int uim_Program { get; set; }
        public Nullable<int> uim_IdWzorca { get; set; }
        public string uim_Progid { get; set; }
        public int uim_TypKontekstu { get; set; }
        public string uim_Kontekst { get; set; }
        public string uim_Tytul { get; set; }
        public string uim_Podtytul { get; set; }
        public string uim_VespDef { get; set; }
        public string uim_XSLT { get; set; }
        public bool uim_HTML { get; set; }
        public int uim_SchematKolorow { get; set; }
        public bool uim_FiltrWymagany { get; set; }
        public int uim_StatusNowosci { get; set; }
        public string uim_Opis { get; set; }
        public bool uim_Ukryte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ui_Funkcja> ui_Funkcja { get; set; }
        public virtual ui_Kolor ui_Kolor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ui_Modul> ui_Modul1 { get; set; }
        public virtual ui_Modul ui_Modul2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ui_ModulPowiazany> ui_ModulPowiazany { get; set; }
    }
}
